language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LkRKPHkYSxKe8BBCoHLdvSZfi6bvpE8dSE2tSyoRolzimkXM1MZZJqGlDNSTDnMRHb7EG6Gg11xPlN7/8wHopAGVJHevjUcUP62kbBZjTFxsI2txEnah/4JY0SSpsdM4W+00d7EnwdbS7AlvkMKGrvie1lW6JvKMTDixb0PoPgt361GVBjnQTBi8bcsToKeJlOyai2vQoF3SZj61+FAxrPgGxBwJqKNfpo4S4OpFWIaN+M0CEjSUaScYFk7TSuAvJA/fqEj8LQlvIy0ai2huiTmK46+B9Xmn0zrBbfRf98+Y8TsmEmQPDEdOGzcrjIMiZh2OPgLp5iy+6yrPus10RzPLiUqHRuqEO8kXD7m8VD+xM1X3Q0Orjyvh9vd+KsZpOi8Cft0VIKqwkbGieoi5y+TsSDudaTmAYCBqiz6jTtlXKjiAsfF7FzegYRA7JCrt7e/BZbGZ5t7w7vj21Ch316/pZvZMF9B+HoEyul/AaezQHeRlEjfADSNF9q6YCHD3SSvbwNNGGOh4AM5OyUE1xTSzF2EtfkUwGOR/qc9/TbRziaWsyBpFCX//pws41vESZKB2qigTdHPmIuFjdeuvL8hQ1IyRUhePmEC0BKgM+edD9C/qchopsqUIsE5cxpptZTaDJOTBZKIN8+2yuOgZShQLZrTpo1P1Qz/YrPr48MQ=
  file:
    - 'cuss.js'
    - 'cuss.min.js'
  on:
    tags: true
